- name: "ensure CNI directory existance"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
  with_items:
    - "/etc/cni/net.d"
    - "/opt/cni/bin"
- name: add settings
  template:
    dest: "/etc/cni/net.d/{{ item }}"
    src: "{{ item }}.j2"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "10-bridge.conflist"
    - "99-loopback.conf"
