- name: Install wireguard
  block:
  - name: Check wg exists
    command: which wg
    changed_when: false
  rescue:
  - name: add repo
    apt_repository:
      repo: ppa:wireguard/wireguard
  - name: "install wireguard"
    apt:
      name: wireguard
      state: present
- name: Enable net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: yes
    state: present
