- name: Create wireguard directory
  file:
    path: "/etc/wireguard"
    state: directory
    owner: root
    group: root
    mode: 0600
- name: "check private key existance"
  check_mode: no
  stat:
    path: "/etc/wireguard/{{ wg_interface }}.key"
  register: wg_private_key_stat
- name: Generate private keys
  shell: wg genkey > "/etc/wireguard/{{ wg_interface }}.key"
  register: wireguard_genkey
  when: (not wg_private_key_stat.stat.exists) or wg_regenerate_keys
- name: Read private key
  check_mode: no
  command: "cat /etc/wireguard/{{ wg_interface }}.key"
  register: wireguard_privkey
  changed_when: false
- name: "Set private key fact"
  set_fact:
    wg_private_key: "{{ wireguard_privkey.stdout }}"
- name: Generate public keys
  check_mode: no
  command: "wg pubkey"
  args:
    stdin: "{{ wg_private_key }}"
  register: wireguard_pubkey
  changed_when: false
