- include_tasks: "install_{{ ansible_distribution }}.yml"
- name: Create wireguard directory
  file:
    path: "/etc/wireguard"
    state: directory
    owner: root
    group: root
    mode: 0600
- name: Configuring wireguard
  template:
    src: wg.conf.j2
    dest: "/etc/wireguard/{{ wg_interface }}.conf"
    owner: root
    group: root
    mode: 0600
  notify: "restart wg"
- include_tasks: "keys.yml"
- name: Setup CNI plugin
  block:
    - name: "ensure CNI directory existance"
      file:
        path: "{{ item }}"
        state: directory
        owner: root
      with_items:
      - "/etc/cni/net.d"
      - "/opt/cni/bin"
    - name: add settings
      template:
        dest: "/etc/cni/net.d/{{ item }}"
        src: "{{ item }}.j2"
        owner: root
        group: root
        mode: 0644
      with_items:
      - "10-bridge.conf"
      - "99-loopback.conf"
  when: wg_cni
- name: Starting wireguard
  systemd:
    name: "wg-quick@{{ wg_interface }}"
    enabled: yes
    state: started
