- name: proper wg_mode
  assert:
    that:
      - "wg_mode in ['apply-all', 'scale-clients']"
    msg: "'wg_mode' must be apply-all or scale-clients"
- include_tasks: "install_{{ ansible_distribution }}.yml"
  tags:
  - install
- name: "Fetch key facts"
  include_tasks: "key_facts.yml"
- name: Set allowed IPs
  include_tasks: "allowed_ips.yml"
- name: "Set facts"
  set_fact:
    wg_public_key: "{{ wireguard_pubkey.stdout }}"
    wg_private_ip: "{{ wg_private_ip }}"
    wg_public_ip: "{{ wg_public_ip }}"
    wg_port: "{{ wg_port }}"
    wg_cni: "{{ wg_cni }}"
    wg_change:  "{{ wg_mode == 'apply-all' or (wg_mode =='scale-clients' and wg_public_ip == '') }}"
- name: Configuring wireguard
  tags:
    - config
    - wg-config
  template:
    src: wg.conf.j2
    dest: "/etc/wireguard/{{ wg_interface }}.conf"
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: "restart wg"
  when: wg_change
- name: Setup CNI plugin
  tags:
  - cni
  - wg-cni
  include_tasks: "cni.yml"
  when: wg_cni and wg_change
- name: Integrate with wg operator
  tags:
    - wg-operator
  include_tasks: "wg_operator.yml"
  when: wg_operator_manifest and wg_change
- name: Starting wireguard
  systemd:
    name: "wg-quick@{{ wg_interface }}"
    enabled: yes
    state: started
