- name: proper wg_mode
  assert:
    that:
      - "wg_mode in ['apply-all', 'scale-clients']"
    msg: "'wg_mode' must be apply-all or scale-clients"
- include_tasks: "install_{{ ansible_distribution }}.yml"
  tags:
  - install
- name: "Fetch key facts"
  include_tasks: "key_facts.yml"
- name: Set allowed IPs
  include_tasks: "allowed_ips.yml"
- name: "Set facts"
  set_fact:
    wg_public_key: "{{ wireguard_pubkey.stdout }}"
    wg_private_ip: "{{ wg_private_ip }}"
    wg_public_ip: "{{ wg_public_ip }}"
    wg_port: "{{ wg_port }}"
    wg_cni: "{{ wg_cni }}"
    wg_change:  "{{ wg_mode == 'apply-all' or (wg_mode =='scale-clients' and wg_public_ip == '') }}"
- name: set defaults for wg peer[0]
  set_fact:
    wg_peers_tmp: []
- name: set defaults for wg peer[1]
  set_fact:
    wg_peers_tmp: >
      {{ wg_peers_tmp + [
        {
          "name": item['public_key'],
          "public_ip": "",
          "port": "",
          "post_up": "",
          "post_down": "",
          "private_ip": "",
        } | combine(item)
      ] }}
  with_items: "{{ wg_peers }}"
- name: set defaults for wg peer[2]
  set_fact:
    wg_peers: "{{ wg_peers_tmp }}"
- name: Set wg peer info
  set_fact:
    wg_peers: >
     {{ wg_peers + [ {
        "name": item,
        "public_ip": hostvars[item]['wg_public_ip'],
        "private_ip": hostvars[item]['wg_private_ip'],
        "public_key": hostvars[item]['wg_public_key'],
        "port": hostvars[item]['wg_port'],
        "allowed_ips": hostvars[item]['wg_allowed_ips'],
        "post_up": hostvars[item]['wg_postup'],
        "post_down": hostvars[item]['wg_postdown'],
      }] }}
  with_items: "{{ groups['wireguard'] }}"
  when:
  - item in ansible_play_hosts_all
  - item != inventory_hostname
- name: display known peers
  debug:
    var: wg_peers
- name: Integrate with wg operator
  tags:
    - wg-operator
  include_tasks: "wg_operator.yml"
  when: wg_operator_manifest and wg_change
- name: Configuring wireguard
  tags:
    - config
    - wg-config
  template:
    src: wg.conf.j2
    dest: "/etc/wireguard/{{ wg_interface }}.conf"
    owner: "{{ wg_user }}"
    group: "{{ wg_group }}"
    mode: 0660
    backup: yes
  notify: "restart wg"
  when: wg_change
- name: Setup CNI plugin
  tags:
  - cni
  - wg-cni
  include_tasks: "cni.yml"
  when: wg_cni and wg_change
- name: Starting wireguard
  systemd:
    name: "wg-quick@{{ wg_interface }}"
    enabled: yes
    state: started
